// <copyright file="PreOperationxts_customautonumberCreate.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>1/2/2017 9:01:02 AM</date>
// <summary>Implements the PreOperationxts_customautonumberCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using Microsoft.Xrm.Sdk;
using TSAD.CORE.D365.Entities;
using TSAD.XRM.Framework.Auto365.Plugin;
using TSAD.CORE.D365.COM.AutoNumber.CustomAutoNumber;

namespace TSAD.CORE.D365.COM.AutoNumber.Plugins.CustomAutoNumber
{

    /// <summary>
    /// PreOperationxts_customautonumberCreate Plugin.
    /// </summary>    
    public class PreCustomAutoNumberCreate : Auto365BasePlugin<xts_customautonumber>, IPlugin
    {
        protected PreCustomAutoNumberCreate(string unsecure, string secure) : base(unsecure, secure)
        {
        }

        protected override void ExecuteCrmPlugin(IAuto365TransactionContext<xts_customautonumber> context)
        {
            new CreateCustomAutoNumber(context).Execute();
        }        
    }
}
