// <copyright file="PreCustomAutoNumberUpdate.cs" company="">
// Copyright (c) 2017 All Rights Reserved
// </copyright>
// <author></author>
// <date>1/16/2017 9:33:46 AM</date>
// <summary>Implements the PreCustomAutoNumberUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using Microsoft.Xrm.Sdk;
using TSAD.CORE.D365.COM.AutoNumber.CustomAutoNumber;
using TSAD.CORE.D365.Entities;
using TSAD.XRM.Framework.Auto365.Plugin;

namespace TSAD.CORE.D365.COM.AutoNumber.Plugins.CustomAutoNumber
{

    /// <summary>
    /// PreCustomAutoNumberUpdate Plugin.
    /// </summary>    
    public class PreCustomAutoNumberUpdate : Auto365BasePlugin<xts_customautonumber>, IPlugin
    {
        public PreCustomAutoNumberUpdate(string unsecure = null, string secure = null) : base(unsecure, secure)
        {
        }

        protected override void ExecuteCrmPlugin(IAuto365TransactionContext<xts_customautonumber> context)
        {
            if (context.Input.Attributes.Contains("xts_segmentformat") | context.Input.Attributes.Contains("xts_resettype"))
            {
                new UpdateCustomAutoNumber(context).Execute();
            }
        }
    }
}
